server:
  port: 8091

spring:
  cloud:
    nacos:
      server-addr: 106.53.68.162:8848
    sentinel:
      transport:
        dashboard: 106.53.68.162:8080 #配置Sentinel dashboard控制台服务地址
        port: 8719 #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
