spring:
  application:
    name: goodchoiceoj-backend-gateway
  main:
    web-application-type: reactive
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080 #配置Sentinel dashboard控制台服务地址
        port: 8719 #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
    gateway:
      routes:
        #用户模块
        - id: goodchoiceoj-backend-user-service
          uri:
            lb://goodchoiceoj-backend-user-service
          predicates:
            - Path=/user/**

        #问题模块
        - id: goodchoiceoj-backend-question-service
          uri:
            lb://goodchoiceoj-backend-question-service
          predicates:
            - Path=/question/**

        #判题模块
        - id: goodchoiceoj-backend-judge-service
          uri:
            lb://goodchoiceoj-backend-judge-service
          predicates:
            - Path=/judge/**
server:
  port: 8101

knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2