# 公共配置文件
spring:
  rabbitmq:
    host: localhost
    port: 5672
    password: admin
    username: admin
  application:
    name: goodchoiceoj-backend-judge-service
  #默认 dev 环境
  profiles:
    active: dev

  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080 #配置Sentinel dashboard控制台服务地址
        port: 8719 #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
server:
  address: 0.0.0.0
  port: 8104
  servlet:
    context-path: /judge

##代码沙箱配置
codesandbox:
  type: remote
  #代码沙箱地址
  address: http://192.168.126.132:8091/executeCode



knife4j:
  enable: true




