# 公共配置文件
spring:
  rabbitmq:
    host: localhost
    port: 5672
    password: admin
    username: admin
  application:
    name: goodchoiceoj-backend-question-service
  #默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/goodchoiceoj
    username: root
    password: root
  # Redis 配置
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
  #    lettuce:
  #      pool:
  #        max-active: 8
  #        max-idle: 8
  #        min-idle: 0
  #    password: Lhx20021030!
  servlet:
    multipart:
      max-file-size: 10MB
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  address: 0.0.0.0
  port: 8103
  servlet:
    context-path: /question
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
        path: /
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

##代码沙箱配置
codesandbox:
  type: remote
  #  #代码沙箱地址
  address: http://192.168.126.132:8091/executeCode


knife4j:
  enable: true




