# 公共配置文件
spring:
  application:
    name: goodchoiceoj-backend-user-service

  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.116.197.73:35623/goodchoiceoj_user
    username: root
    password: Rd@s2135f
  # Redis 配置
  redis:
    database: 1
    host: 114.116.213.137
    port: 6379
    timeout: 5000
    password: 123456
  servlet:
    multipart:
      max-file-size: 10MB
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
server:
  address: 0.0.0.0
  port: 9002
  servlet:
    context-path: /user
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
        path: /
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

knife4j:
  enable: true




